namespace AstraLab.Core.Domains.Analytics
{
    /// <summary>
    /// Classifies whether an insight was generated by AI or by the system itself.
    /// </summary>
    public enum InsightSourceType
    {
        /// <summary>
        /// Indicates that the insight was generated by an AI workflow.
        /// </summary>
        AiGenerated = 1,

        /// <summary>
        /// Indicates that the insight was generated by a deterministic system workflow.
        /// </summary>
        SystemGenerated = 2
    }
}
