namespace AstraLab.Core.Domains.Analytics
{
    /// <summary>
    /// Classifies whether a report was generated by AI or by the system itself.
    /// </summary>
    public enum ReportSourceType
    {
        /// <summary>
        /// Indicates that the report was generated by an AI workflow.
        /// </summary>
        AiGenerated = 1,

        /// <summary>
        /// Indicates that the report was generated by a deterministic system workflow.
        /// </summary>
        SystemGenerated = 2
    }
}
