import type { ThemeConfig } from "antd";
import { theme } from "antd";

export const appTheme: ThemeConfig = {
  algorithm: theme.darkAlgorithm,
  token: {
    colorPrimary: "#ff7a1a",
    colorInfo: "#2f8cff",
    colorSuccess: "#31d67b",
    colorWarning: "#f5c244",
    colorError: "#ff5f5f",
    colorTextBase: "#f4f7fb",
    colorBgBase: "#0a1120",
    colorBgLayout: "#09111f",
    colorBgContainer: "#111a2d",
    colorBgElevated: "#141f35",
    colorBorder: "#223251",
    colorBorderSecondary: "#1c2a43",
    borderRadius: 16,
    borderRadiusLG: 24,
    borderRadiusSM: 12,
    controlHeight: 48,
    controlHeightLG: 56,
    fontFamily: "'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
    boxShadowSecondary: "0 24px 80px rgba(0, 0, 0, 0.32)",
  },
  components: {
    Layout: {
      bodyBg: "#09111f",
      headerBg: "transparent",
      siderBg: "transparent",
    },
    Card: {
      colorBgContainer: "#10192b",
      colorBorderSecondary: "#21314d",
      borderRadiusLG: 24,
    },
    Button: {
      borderRadius: 14,
      borderRadiusLG: 16,
      controlHeight: 48,
      controlHeightLG: 56,
      colorPrimary: "#ff7a1a",
      colorPrimaryHover: "#ff9240",
      colorPrimaryActive: "#e46912",
      defaultBg: "#1a2540",
      defaultBorderColor: "#2a3a5d",
      defaultColor: "#f4f7fb",
      contentFontSize: 16,
      fontWeight: 600,
    },
    Input: {
      colorBgContainer: "#0f1728",
      activeBg: "#0f1728",
      hoverBg: "#0f1728",
      addonBg: "#0f1728",
      colorBorder: "#243451",
      hoverBorderColor: "#2d446d",
      activeBorderColor: "#2f8cff",
      activeShadow: "0 0 0 3px rgba(47, 140, 255, 0.14)",
      colorTextPlaceholder: "#60708b",
      colorText: "#f4f7fb",
      borderRadius: 14,
      controlHeight: 48,
    },
    Form: {
      labelColor: "#f4f7fb",
      labelFontSize: 14,
    },
    Divider: {
      colorSplit: "#1f2d48",
    },
  },
};
